### ISSUE TITLE
request for access to source code of javascript template file

### ISSUE THREAD

**Issue by JohnnyZhao** [EOSIO/eosio-reference-ios-authenticator-app#13]
When we were debugging ricardian contract rendering, we encountered several errors related to javascript template rendering.

to be specific, it's Eosio/Transactions/contract-template-toolkit.js, a minified js, which makes debugging really difficult and hard to read.

could you provide the un-minified source code of it?

and if there's other similar files in this project, could you provide those also?

Thanks

**Comment by JohnnyZhao** [comment]
found it: https://github.com/EOSIO/ricardian-template-toolkit

**Comment by brandonfancher** [comment]
Sorry we didn't point you in the right direction earlier! Glad you found the RTT.
